# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b384356442378bae03863e5214992d3c"
name = "Heeiz App"
application_url = "https://heeiz-fulfillment.up.railway.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = ["app/scopes_update"]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
  uri = "/webhooks"


[access.admin]
direct_api_mode = "online"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_products"

[auth]
redirect_urls = [
  "https://heeiz-fulfillment.up.railway.app/auth/callback",
  "https://heeiz-fulfillment.up.railway.app/auth/shopify/callback",
  "https://heeiz-fulfillment.up.railway.app/api/auth"
]
